import { mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root=process.cwd();
const routes={
  '/':['index.html','text/html; charset=utf-8'],
  '/styles.css':['src/web/styles.css','text/css; charset=utf-8'],
  '/web/app.js':['src/web/app.js','text/javascript; charset=utf-8'],
  '/core/board.js':['src/core/board.js','text/javascript; charset=utf-8'],
  '/core/fen.js':['src/core/fen.js','text/javascript; charset=utf-8'],
  '/core/rules.js':['src/core/rules.js','text/javascript; charset=utf-8'],
  '/engine/evaluate.js':['src/engine/evaluate.js','text/javascript; charset=utf-8'],
  '/engine/search.js':['src/engine/search.js','text/javascript; charset=utf-8'],
  '/vision/schema.js':['src/vision/schema.js','text/javascript; charset=utf-8'],
  '/vision/reconcile.js':['src/vision/reconcile.js','text/javascript; charset=utf-8'],
  '/overlay/geometry.js':['src/overlay/geometry.js','text/javascript; charset=utf-8'],
  '/overlay/draw.js':['src/overlay/draw.js','text/javascript; charset=utf-8'],
  '/app/analysis-controller.js':['src/app/analysis-controller.js','text/javascript; charset=utf-8'],
  '/app/video.js':['src/app/video.js','text/javascript; charset=utf-8']
};
const assets={};
for(const [route,[file,type]] of Object.entries(routes)) assets[route]={body:await readFile(resolve(root,file),'utf8'),type};
const runtime=await readFile(resolve(root,'src/worker-runtime.js'),'utf8');
const banner=`// Generated by scripts/build.mjs. Do not edit dist directly.\nglobalThis.__XIANGQI_ASSETS__=${JSON.stringify(assets)};\n`;
await rm(resolve(root,'dist'),{recursive:true,force:true}); await mkdir(resolve(root,'dist'),{recursive:true});
await writeFile(resolve(root,'dist/worker.js'),banner+runtime);
console.log(`build: dist/worker.js (${Buffer.byteLength(banner+runtime)} bytes, ${Object.keys(assets).length} embedded routes)`);
